train_file: /mnt/petrelfs/wuchaoyi/class-to-text/Whole_dataset/train/
valid_file: /mnt/petrelfs/wuchaoyi/class-to-text/Whole_dataset/valid/
test_file: /mnt/petrelfs/wuchaoyi/class-to-text/Whole_dataset/test/

mode: 'whole'
Tokens: 64
batch_size: 128
momentum: 0.995
alpha: 0.4
d_model: 256
res_base_model: 'resnet50'
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4 
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
shuffle_ratio: 0.5
optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 100, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}




